const INCREMENT_COUNTER = 'counter/INCREMENT';
const UPDATE_COUNTER = 'counter/UPDATE';
const WATCH_COUNTER = 'counter/WATCH';

module.exports = {
    INCREMENT_COUNTER: INCREMENT_COUNTER,
    UPDATE_COUNTER: UPDATE_COUNTER,
    WATCH_COUNTER: WATCH_COUNTER
};
