---
apiVersion: v1
kind: ConfigMap
metadata:
  name: l5d-config
data:
  config.yaml: |-
    admin:
      port: 9990

    namers:
    - kind: io.l5d.k8s
      experimental: true
      host: localhost
      port: 8001

    routers:

    - protocol: http
      label: outgoing
      baseDtab: |
        /frontend=>/#/io.l5d.k8s/default/external/frontend;
        /backend=>/#/io.l5d.k8s/default/http/backend;
        /xebigo/*=>/frontend;
        /xebigo/api=>/backend/api;
        /xebigo/socket.io=>/backend/socket.io;
        /http/*/*/xebigo.cbnserver.com=>/xebigo
      interpreter:
        kind: default
        transformers:
        - kind: io.l5d.k8s.daemonset
          namespace: default
          port: incoming
          service: l5d
      servers:
      - port: 4140
        ip: 0.0.0.0
      responseClassifier:
        kind: io.l5d.retryableRead5XX
      client:
        retries:
          budget:
            minRetriesPerSec: 5
            percentCanRetry: 0.5
            ttlSecs: 15
          backoff:
            kind: jittered
            minMs: 10
            maxMs: 10000
    - protocol: http
      label: incoming
      dstPrefix: /
      identifier:
        kind: io.l5d.header
        header: l5d-dst-concrete
      interpreter:
        kind: default
        transformers:
        - kind: io.l5d.k8s.localnode
      servers:
      - port: 4141
        ip: 0.0.0.0
      responseClassifier:
        kind: io.l5d.retryableRead5XX
      client:
        retries:
          budget:
            minRetriesPerSec: 5
            percentCanRetry: 0.5
            ttlSecs: 15
          backoff:
            kind: jittered
            minMs: 10
            maxMs: 10000
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: l5d
  name: l5d
spec:
  template:
    metadata:
      labels:
        app: l5d
    spec:
      volumes:
      - name: l5d-config
        configMap:
          name: "l5d-config"
      containers:
      - name: l5d
        image: buoyantio/linkerd:0.8.1
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        args:
        - "/io.buoyant/linkerd/config/config.yaml"
        ports:
        - name: incoming
          containerPort: 4141
          hostPort: 4141
        - name: outgoing
          containerPort: 4140
          hostPort: 4140
        - name: admin
          containerPort: 9990
          hostPort: 9990
        volumeMounts:
        - name: "l5d-config"
          mountPath: "/io.buoyant/linkerd/config"
          readOnly: true
      - name: kubectl
        image: buoyantio/kubectl:v1.4.0
        args:
        - "proxy"
        - "-p"
        - "8001"
---
apiVersion: v1
kind: Service
metadata:
  name: l5d
spec:
  selector:
    app: l5d
  type: LoadBalancer
  ports:
  - name: outgoing
    port: 80
    targetPort: 4140
  - name: incoming
    port: 4141
  - name: admin
    port: 9990